export const companyTypes = {
    GET_COMPANY: 'GET_COMPANY',
    SET_COMPANY: 'SET_COMPANY',
    TALENTS_COMPANY: 'TALENTS_COMPANY',
    SAVE_COMPANY_ID: 'SAVE_COMPANY_ID',
    ADD_COMPANY : 'ADD_COMPANY',
    EDIT_COMPANY: 'EDIT_COMPANY',
    DELETE_COMPANY : "DELETE_COMPANY",
  }