export const talentsTypes = {
  // TALENT_REGISTER: "TALENT_REGISTER",
  // TALENT_LOGIN: "TALENT_lOGIN",
  // TALENT_LOGOUT: "TALENT_LOGOUT",
  TALENT_REGISTER_ERROR: "TALENT_REGISTER_ERROR",

  TALENTS_GET: 'TALENTS_GET',
  // TALENTS_ADD: 'TALENTS_ADD',
  TALENTS_FILTERED: 'TALENTS_FILTERED'
}

export const userTypes = {
  USER_REGITER: "USER_REGITER",
  USER_LOGIN: "USER_lOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  USER_COMPLETETALENTS: "USER_COMPLETETALENTS",
};

export const userRegisterTypes = {
 USERREGISTER_GET: 'USERREGISTER_GET',
};