export const talentsTypes = {
  TALENTS_GET: 'TALENTS_GET',
  GET_TALENT: 'GET_TALENT',
  TALENTS_FILTERED: 'TALENTS_FILTERED',
  SAVE_TALENT_ID: 'SAVE_TALENT_ID'
}

export const userTypes = {
  USER_REGITER: "USER_REGITER",
  USER_LOGIN: "USER_lOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  USER_COMPLETETALENTS: "USER_COMPLETETALENTS",
};


