export const validateTalents = {
     GET_TALENT: 'GET_TALENT',
    TALENTS_FILTERED: 'TALENTS_FILTERED',
    SAVE_TALENT_ID: 'SAVE_TALENT_ID',
    EDIT_TALENTS: 'EDIT_TALENTS',
    DELETE_TALENTS : "DELETE_TALENTS",
    
  }

  